/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BreadCrumb: typeof import('./src/components/BreadCrumb.vue')['default']
    Breadcrump: typeof import('./src/components/breadcrump.vue')['default']
    BreadCrump: typeof import('./src/components/BreadCrump.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IFeArrowLeft: typeof import('~icons/fe/arrow-left')['default']
    'IMaterialSymbols:home': typeof import('~icons/material-symbols/home')['default']
    'IMaterialSymbols:search': typeof import('~icons/material-symbols/search')['default']
    LayoutAdminHeader: typeof import('./src/components/layout/Admin/Header.vue')['default']
    LayoutAdminMenuMobile: typeof import('./src/components/layout/Admin/MenuMobile.vue')['default']
    LayoutAdminSidebar: typeof import('./src/components/layout/Admin/Sidebar.vue')['default']
    LayoutAdminWrapMenu: typeof import('./src/components/layout/Admin/WrapMenu.vue')['default']
    LayoutUserHeader: typeof import('./src/components/layout/User/Header.vue')['default']
    LayoutUserMenumMobile: typeof import('./src/components/layout/User/MenuMobile.vue')['default']
    LayoutUserMenuMobile: typeof import('./src/components/layout/User/MenuMobile.vue')['default']
    LayoutUserSidebar: typeof import('./src/components/layout/User/Sidebar.vue')['default']
    LayoutUserWrapMenu: typeof import('./src/components/layout/User/WrapMenu.vue')['default']
    NBreadcrumb: typeof import('naive-ui')['NBreadcrumb']
    NBreadcrumbItem: typeof import('naive-ui')['NBreadcrumbItem']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModalProvider: typeof import('naive-ui')['NModalProvider']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
