/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BreadCrumb: typeof import('./src/components/BreadCrumb.vue')['default']

    ElderlyUserModalCheckupElderly: typeof import('./src/components/elderly/user/modal-checkup-elderly.vue')['default']

    IFeArrowLeft: typeof import('~icons/fe/arrow-left')['default']
    'ILsicon:arrowRightFilled': typeof import('~icons/lsicon/arrow-right-filled')['default']
    'IMaterialSymbols:search': typeof import('~icons/material-symbols/search')['default']
    LayoutAdminHeader: typeof import('./src/components/layout/Admin/Header.vue')['default']
    LayoutAdminMenuMobile: typeof import('./src/components/layout/Admin/MenuMobile.vue')['default']
    LayoutAdminSidebar: typeof import('./src/components/layout/Admin/Sidebar.vue')['default']
    LayoutAdminWrapMenu: typeof import('./src/components/layout/Admin/WrapMenu.vue')['default']
    LayoutUserHeader: typeof import('./src/components/layout/User/Header.vue')['default']
    LayoutUserMenuMobile: typeof import('./src/components/layout/User/MenuMobile.vue')['default']
    LayoutUserSidebar: typeof import('./src/components/layout/User/Sidebar.vue')['default']
    LayoutUserWrapMenu: typeof import('./src/components/layout/User/WrapMenu.vue')['default']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDatePicker: typeof import('naive-ui')['NDatePicker']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NImage: typeof import('naive-ui')['NImage']
    NInput: typeof import('naive-ui')['NInput']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModalProvider: typeof import('naive-ui')['NModalProvider']
    NPagination: typeof import('naive-ui')['NPagination']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
