services:
  catatsehat-frontend:
    image: yudhapwa/fe-catat-sehat:dev
    container_name: catatsehat-frontend
    ports:
      - "5173:80"
    restart: on-failure
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost/" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s
