export const API = {
  AUTH_USER_LOGIN: '/v1/user/auth/sign-in',
  AUTH_USER_SIGNUP: '/v1/user/auth/sign-up',
  AUTH_ADMIN_SIGNIN: '/v1/admin/auth/sign-in',
  AUTH_POST_RESEND_OTP: '/v1/user/auth/resend-otp',
  AUTH_POST_VERIFY_OTP: '/v1/user/auth/verify-otp',
  AUTH_POST_VERIFY_FORGOT_OTP: '/v1/user/auth/forgot-pin/reset-pin',
  AUTH_POST_RESEND_FORGOT_OTP: '/v1/user/auth/forgot-pin/resend-otp',
  AUTH_POST_REQUEST_FORGOT_OTP: '/v1/user/auth/forgot-pin/request-otp',
  ADMIN_POST_ARTICLE: '/v1/article',
  USER_GET_ARTICLE: '/v1/article',
  USER_GET_ARTICLE_ID: '/v1/article/{id}',
  ADMIN_DELETE_ARTICLE: '/v1/article/{id}',
  ADMIN_PUT_ARTICLE: '/v1/article/{id}',
  ADMIN_POST_ADMIN: '/v1/admin',
  ADMIN_GET_ADMIN: '/v1/admin',
  ADMIN_GET_ADMIN_ID: '/v1/admin/{id}/detail',
  ADMIN_DELETE_ADMIN: '/v1/admin/{id}',
  ADMIN_PUT_ADMIN: '/v1/admin/{id}',
  ADMIN_GET_HEALTH_POST: '/v1/healthPost',
  USER_POST_ELDERLY: '/v1/elderly',
  USER_GET_ELDERLY: '/v1/elderly',
  ADMIN_GET_ELDERLY: '/v1/elderly',
  USER_GET_ELDERLY_ID: '/v1/elderly/{id}',
  ADMIN_GET_ELDERLY_ID: '/v1/elderly/{id}',
  USER_DELETE_ELDERLY_ID: '/v1/elderly/{id}',
  USER_PUT_ELDERLY_ID: '/v1/elderly/{id}'
}
