name: Development Pipeline

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push frontend Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: yudhapwa/fe-catat-sehat:dev
          build-args: |
            # VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}
            VITE_API_BASE_URL=/api
            
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Copy files to VPS
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "."
          target: "/home/wawan/catatsehat/tmp"

      - name: Deploy to Prod Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/wawan/catatsehat/tmp

            # echo "docker_password" | docker login -u "docker_username" --password-stdin

            # Stop dan hapus container
            docker compose -p dev -f docker-compose.yml down --remove-orphans

            # Hapus image
            docker rmi yudhapwa/fe-catat-sehat:dev || true

            # Pull image 
            docker pull yudhapwa/fe-catat-sehat:dev

            # Logout
            # docker logout

            # Restart
            docker compose -p dev -f docker-compose.yml up -d

            # Bersih cache/temp
            rm -rf /home/wawan/catatsehat/tmp/*
